# -*- coding: utf-8 -*-
"""ytbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6PKgWUvI7vNMpWI5EUM7CCCfX3tTioi
"""

!pip install vk_api
!pip3 install youtube-search-python

import os
import vk_api
from random import randrange
from vk_api.longpoll import VkEventType, VkLongPoll
from youtubesearchpython import VideosSearch

TOKEN = 'vk1.a.OnSJdGzkye0jOUmN2ZJQMFW3R8nm6X0YVmeLZKXW2io25wIaaG_aU2yVXRjFT0lQdmjQIGhBbzb26hzdvi3iU_nVC1GSAm5HxtZC2YsEYVPz9OcWuSZtDfJqROLrWXTi1Paasw8897w1zzzZsD7Bg8zNnIXCIwrysiMUoP0ctSwS9ioR3oTmNrg8DGeD9gJ7DTfe7on82VS0XOi_frw2PA'

vk_session = vk_api.VkApi(token=TOKEN)
longpoll = VkLongPoll(vk_session)
vk = vk_session.get_api()

for event in longpoll.listen():
  if event.type == VkEventType.MESSAGE_NEW and event.to_me and event.text.lower():
    if event.from_user:
      link = VideosSearch(event.text, limit = 1).result()['result'][0]['link']
      vk.messages.send(user_id=event.user_id, message=link, random_id= randrange(1,1000000))